package org.three

     external object THREE {

        val REVISION: String
        val CullFaceNone: Int
        val CullFaceBack: Int
        val CullFaceFront: Int
        val CullFaceFrontBack: Int
        val FrontFaceDirectionCW: Int
        val FrontFaceDirectionCCW: Int
        val BasicShadowMap: Int
        val PCFShadowMap: Int
        val PCFSoftShadowMap: Int
        val FrontSide: Int
        val BackSide: Int
        val DoubleSide: Int
        val FlatShading: Int
        val SmoothShading: Int
        val NoColors: Int
        val FaceColors: Int
        val VertexColors: Int
        val NoBlending: Int
        val NormalBlending: Int
        val AdditiveBlending: Int
        val SubtractiveBlending: Int
        val MultiplyBlending: Int
        val CustomBlending: Int
        val AddEquation: Int
        val SubtractEquation: Int
        val ReverseSubtractEquation: Int
        val MinEquation: Int
        val MaxEquation: Int
        val ZeroFactor: Int
        val OneFactor: Int
        val SrcColorFactor: Int
        val OneMinusSrcColorFactor: Int
        val SrcAlphaFactor: Int
        val OneMinusSrcAlphaFactor: Int
        val DstAlphaFactor: Int
        val OneMinusDstAlphaFactor: Int
        val DstColorFactor: Int
        val OneMinusDstColorFactor: Int
        val SrcAlphaSaturateFactor: Int
        val NeverDepth: Int
        val AlwaysDepth: Int
        val LessDepth: Int
        val LessEqualDepth: Int
        val EqualDepth: Int
        val GreaterEqualDepth: Int
        val GreaterDepth: Int
        val NotEqualDepth: Int
        val MultiplyOperation: Int
        val MixOperation: Int
        val AddOperation: Int
        val NoToneMapping: Int
        val LinearToneMapping: Int
        val ReinhardToneMapping: Int
        val Uncharted2ToneMapping: Int
        val CineonToneMapping: Int
        val UVMapping : Int
        val CubeReflectionMapping: Int
        val CubeRefractionMapping: Int
        val EquirectangularReflectionMapping: Int
        val EquirectangularRefractionMapping: Int
        val SphericalReflectionMapping: Int
        val CubeUVReflectionMapping: Int
        val CubeUVRefractionMapping: Int
        val RepeatWrapping: Int
        val ClampToEdgeWrapping: Int
        val MirroredRepeatWrapping: Int
        val NearestFilter: Int
        val NearestMipMapNearestFilter: Int
        val NearestMipMapLinearFilter: Int
        val LinearFilter: Int
        val LinearMipMapNearestFilter: Int
        val LinearMipMapLinearFilter: Int
        val UnsignedByteType: Int
        val ByteType: Int
        val ShortType: Int
        val UnsignedShortType: Int
        val IntType: Int
        val UnsignedIntType: Int
        val FloatType: Int
        val HalfFloatType: Int
        val UnsignedShort4444Type: Int
        val UnsignedShort5551Type: Int
        val UnsignedShort565Type: Int
        val UnsignedInt248Type: Int
        val AlphaFormat: Int
        val RGBFormat: Int
        val RGBAFormat: Int
        val LuminanceFormat: Int
        val LuminanceAlphaFormat: Int
        val RGBEFormat: Int
        val DepthFormat: Int
        val DepthStencilFormat: Int
        val RGB_S3TC_DXT1_Format: Int
        val RGBA_S3TC_DXT1_Format: Int
        val RGBA_S3TC_DXT3_Format: Int
        val RGBA_S3TC_DXT5_Format: Int
        val RGB_PVRTC_4BPPV1_Format: Int
        val RGB_PVRTC_2BPPV1_Format: Int
        val RGBA_PVRTC_4BPPV1_Format: Int
        val RGBA_PVRTC_2BPPV1_Format: Int
        val RGB_ETC1_Format: Int
        val LoopOnce: Int
        val LoopRepeat: Int
        val LoopPingPong: Int
        val InterpolateDiscrete: Int
        val InterpolateLinear: Int
        val InterpolateSmooth: Int
        val ZeroCurvatureEnding: Int
        val ZeroSlopeEnding: Int
        val WrapAroundEnding: Int
        val TrianglesDrawMode: Int
        val TriangleStripDrawMode: Int
        val TriangleFanDrawMode: Int
        val LinearEncoding: Int
        val sRGBEncoding: Int
        val GammaEncoding: Int
        val RGBEEncoding: Int
        val LogLuvEncoding: Int
        val RGBM7Encoding: Int
        val RGBM16Encoding: Int
        val RGBDEncoding: Int
        val BasicDepthPacking: Int
        val RGBADepthPacking: Int
        
    }

